### ISSUE TITLE
VitroLib build broken on develop

### ISSUE THREAD

**Issue by rjyounes** [rjyounes/vitrolib#129]
In LCNAFImpl.createConcept():

		HashMap<String, Object> additionalInfo = getRWOInfo(termResult);
		concept.setAdditionalInformation(additionalInfo);

In class Concept:
public void setAdditionalInformation(HashMap<String, String> info) {
	this.additionalInformation = info;
}

The maps are of non-matching types.

**Comment by hudajkhan** [comment]
This is updated on develop to work correctly.
