### ISSUE TITLE
ARM custom list view: binding

### ISSUE THREAD

**Issue by rjyounes** [rjyounes/vitrolib#182]

**Comment by rjyounes** [comment]
Here and in other list view queries: you need to get the rdfs:label for the resource, else the local name will display. Or maybe there are no labels on these resources? - in which case ignore this remark.

**Comment by rjyounes** [comment]
Also: do you really want notes showing in the list view? If the notes are more than a few words, you might not want to include them. Applies here and to some others as well.

**Comment by sfolsom** [comment]
I don't think Bindings have a label based on the SHACL, but I'll check again for each. I wavered about notes; I guess just noting a type of binding would be enough.

**Comment by sfolsom** [comment]
Ready for @hudajkhan to review.

**Comment by hudajkhan** [comment]
updated crm namespace.
