### ISSUE TITLE
General notes

### ISSUE THREAD

**Issue by rjrendall** [rjyounes/vitrolib#32]
Several specific types of notes are implemented at the moment, but looking at the ontology I think we should be able to enter a general note as well (bib.ld4l.org/ontology.html#note), certainly for works and instances and probably for other things as well.  I had information I wanted to enter that didn't fit under any of the available note categories.

**Comment by rjyounes** [comment]
The ontology loaded into the VitroLib sandbox is the LD4L phase 1 ontology, which will not be used in the final product. It's not worth paying attention to ontology support on the sandbox.
