### ISSUE TITLE
Agent instance unexpectedly deleted when modifying contributor to a Work

### ISSUE THREAD

**Issue by daveneiman** [rjyounes/vitrolib#37]
A foaf:Agent is deleted from the triple store when updating the Contributor custom form for a Work.
To replicate:
Create a ld4l:Work
Click Contributors tab
Click '+' to create a new contributor
Select any Contributor Role
Select Person Agent Type (probably any type would work)
Enter a name in the Agent text box
Click Create Entry
--> The contributor should then be visible on the Work page
Click the edit icon for this new contributor
Click the Save Changes button
--> The Agent is no longer visible on the Work page
--> The Agent is no longer in the system

There are like other permutations of the above steps that replicate this bug.

**Comment by daveneiman** [comment]
It appears the Agent instance is still in the triple store when doing a DESCRIBE SPARQL query yet there is no longer a label. However, there is still the ld4l:isAgentOf property.

**Comment by hudajkhan** [comment]
The custom forms have since been changed.  Any bugs related to those should be opened in a new issue.
