### ISSUE TITLE
OpenAnnotation classes not showing in vitrolib admin ontology page

### ISSUE THREAD

**Issue by daveneiman** [rjyounes/vitrolib#41]
Though there are 2 oa-related files deployed to <vitrolib-home>/rdf/tbox/filegraph/, only object properties show, not classes.

**Comment by daveneiman** [comment]
Before ontology update in vitrolib, OA classes were defined in ld4l-bib.rdf as <owl:Class ...> elements whereas in the current code they are defined in oa.2016-11.12.rdf as <rdfs:Class ...>elements. Wondering if this could be the difference.

**Comment by hudajkhan** [comment]
That was the issue I believe.  Typing them as owl:Classes seems to have resolved this.
