### ISSUE TITLE
Error adding new work

### ISSUE THREAD

**Issue by rjyounes** [rjyounes/vitrolib#75]
On develop branch: 

Error message: java.lang.Exception: Errors processing required N3. The EditConfiguration should be setup so that if a submission passes validation, there will not be errors in the required N3. [line: 7, col: 19] Triples not terminated by DOT N3: <http://localhost:8080/vitrolib/individual/n7897> a <http://bib.ld4l.org/ontology/AuthorActivity> ; <http://www.w3.org/2000/01/rdf-schema#label> "Author" ; <http://bib.ld4l.org/ontology/hasAgent> <>SUBMITTED VALUE WAS BLANK<> ; <http://bib.ld4l.org/ontology/isActivityOf> <http://localhost:8080/vitrolib/individual/n2805> . <http://localhost:8080/vitrolib/individual/n3652> <http://www.w3.org/2000/01/rdf-schema#label> "Pride and Prejudice"^^<http://www.w3.org/2001/XMLSchema#string> ; <http://id.loc.gov/ontologies/bibframe/titleOf> <http://localhost:8080/vitrolib/individual/n4228> ; <http://purl.org/dc/terms/hasPart> <http://localhost:8080/vitrolib/individual/n5301> . <http://localhost:8080/vitrolib/individual/n4228> a <http://id.loc.gov/ontologies/bibframe/Instance> ; <http://id.loc.gov/ontologies/bibframe/instanceOf> <http://localhost:8080/vitrolib/individual/n2805> ; <http://id.loc.gov/ontologies/bibframe/title> <http://localhost:8080/vitrolib/individual/n3652> . <>SUBMITTED VALUE WAS BLANK<> a <http://xmlns.com/foaf/0.1/Person> ; <http://www.w3.org/2000/01/rdf-schema#label> "Austen, Jane"^^<http://www.w3.org/2001/XMLSchema#string> ; <http://bib.ld4l.org/ontology/isAgentOf> <http://localhost:8080/vitrolib/individual/n7897> . <http://localhost:8080/vitrolib/individual/n2805> <http://bib.ld4l.org/ontology/hasActivity> <http://localhost:8080/vitrolib/individual/n7897> ; <http://id.loc.gov/ontologies/bibframe/hasInstance> <http://localhost:8080/vitrolib/individual/n4228> . <http://localhost:8080/vitrolib/individual/n5301> a <http://bib.ld4l.org/ontology/MainTitleElement> ; <http://www.w3.org/2000/01/rdf-schema#label> "Pride and Prejudice"^^<http://www.w3.org/2001/XMLSchema#string> ; <http://purl.org/dc/terms/isPartOf> <http://localhost:8080/vitrolib/individual/n3652> .

**Comment by rjyounes** [comment]
Note: the same error occurs when adding an Activity from an existing Work page.

**Comment by hudajkhan** [comment]
I believe this has been fixed.  I'll create a separate issue for activity creation from work page.  Feel free to reopen if need be.
