### ISSUE TITLE
Error adding new instance

### ISSUE THREAD

**Issue by rjyounes** [rjyounes/vitrolib#76]
When clicking on button to create new instance from home page, I get an error. Excerpt below:

Error message: TemplateException creating processing environment

Stack trace (full trace available in the vivo log): edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper$TemplateProcessingException: TemplateException creating processing environment at edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper.processTemplate(TemplateProcessingHelper.java:60) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.TemplateProcessingHelper.processTemplate(TemplateProcessingHelper.java:37) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.processTemplate(FreemarkerHttpServlet.java:494) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.processTemplateToString(FreemarkerHttpServlet.java:500) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doTemplate(FreemarkerHttpServlet.java:273) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doResponse(FreemarkerHttpServlet.java:233) at edu.cornell.mannlib.vitro.webapp.controller.freemarker.FreemarkerHttpServlet.doGet(FreemarkerHttpServlet.java:107) at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at

**Comment by hudajkhan** [comment]
I believe this has been fixed as adding new work + instance is functioning at present.  Feel free to reopen if need be.
