### ISSUE TITLE
Create custom form and display for title

### ISSUE THREAD

**Issue by hudajkhan** [rjyounes/vitrolib#84]
Adding bf:Title to work, instance, item
Also enable editing of title
Also ensure saved title shows on profile page properly (list views/prop statement files)

**Comment by zimeon** [comment]
Feedback in meeting is that setting the title should update `rdfs:label`

**Comment by hudajkhan** [comment]
code working on translateshacl branch.  Will merge into develop and deploy on VitroLib/review with group before closing.
