### ISSUE TITLE
Remove display/form for preferred title

### ISSUE THREAD

**Issue by hudajkhan** [rjyounes/vitrolib#85]
Adding and editing preferred title for work, instance, item
Displaying preferred title on profile pages for work, instance, item

**Comment by zimeon** [comment]
Decision in meeting is that preferred title should not appear on the forms.

**Comment by hudajkhan** [comment]
Will remove manually from faux configuration for now

**Comment by hudajkhan** [comment]
Kept the configuration but updated the template to not show preferred title.
